### ISSUE TITLE
Installation Instructions?

### ISSUE THREAD

**Issue by X3msnake** [AkiraNorthstar/download_threadcharts#1]
Greetings Master

Can you share on the readme information on how to install and use these resources.

Thanks :+1:

**Comment by AkiraNorthstar** [comment]
As normal extension:
- download tarball or clone repository
- unpack / copy files to .config/inkscape/extensions/.
- Restart / start inkscape.
- Extension -> Embroidery -> ThreadCharts...
Please let me know if anything goes wrong.

**Comment by X3msnake** [comment]
It's Working, thanks :)

I will bundle this with the next version of the VM


I contribute back with some ilustrations ;

![virtualbox_dietpi_inkstitch_1 2 0_22_02_2018_16_48_50](https://user-images.githubusercontent.com/11083514/36551788-54a0a94c-17f0-11e8-9dbe-d840145b1aa0.png)

![virtualbox_dietpi_inkstitch_1 2 0_22_02_2018_16_49_39](https://user-images.githubusercontent.com/11083514/36551869-8342930a-17f0-11e8-9f38-165b8e81c590.png)

After Downloading restart inkscape

![virtualbox_dietpi_inkstitch_1 2 0_22_02_2018_16_50_24](https://user-images.githubusercontent.com/11083514/36551877-86535840-17f0-11e8-97af-0f82c39b3b22.png)

Your new colour pallets are now available from the pallet selector
